Significant-Gravitas/Auto-GPT-Benchmarks

agbenchmark/benchmark/challenges/Challenge.py
agbenchmark/benchmark/challenges/retrieval/r1_test.py
data/README.md
data/retrieval/r1_test_data_0.json
data/retrieval/r1_test_data_1.json
examples/basic_gpt_agent.py

A complex DSL format would require a complicated language parser, which would be too costly for us to maintain. JSON is a great format for bridging data files and Python code. When we aim for scalability in this benchmark, JSON files could be more preferable, 
Executable agent example is here https://github.com/Significant-Gravitas/Auto-GPT-Benchmarks/blob/dsl/examples/basic_gpt_agent.py 
Data schema is here https://github.com/Significant-Gravitas/Auto-GPT-Benchmarks/blob/dsl/data/README.md

init first challenge template

---

agbenchmark/challenge.py

Caching deserialization of files so it doesn't rerun every time self.data is called.
- [ x ] I have run the following commands against my code to ensure it passes our linters:
```shell
black .
isort .
mypy .
```

added caching based on file key

---

agbenchmark/agent_interface.py

Before this change stdout would only be printed one line per poll, which means that we may not have read all output by the time the process exited.

Print out all of stdout on each process poll.

---

.github/workflows/superagi.yml

```shell
black .
isort .
mypy .
```

fixing the incorrect addition of superagi

---

.github/workflows/gpt-engineer.yml
agbenchmark/start_benchmark.py

Only run regression tests with mocks, so the tests are faster
```shell
black .
isort .
mypy .
```

Add gpt engineer to ci

---

agbenchmark/agent_interface.py
agbenchmark/config.json

```shell
black .
isort .
mypy .
```

Fix Auto-GPT integration by adding python module as entrypoint

---

.github/workflows/ci.yml

```shell
black .
isort .
mypy .
```

Enable cache again

---

.github/workflows/ci.yml

It turns out the cache would save agbenchmark's state of the first CI run of the day. And this morning there was a bug that duplicated agent calls.
So to avoid issues, I disable caching, we only gain a few seconds from it.
```shell
black .
isort .
mypy .
```

Remove dependencies cache

---

.github/workflows/ci.yml
agbenchmark/conftest.py
agbenchmark/start_benchmark.py

```shell
black .
isort .
mypy .
```

Remove dependencies if a specific test is asked by the user

---

README.md

A repo built for the purpose of benchmarking the performance of agents far and wide, regardless of how they are set up and how they work
Radio chart for each agent coming soon !
:warning: These results are constantly evolving at the moment. We will publish an official benchmark result very soon.
Interface
| Task         | Auto-GPT | gpt-engineer       | mini-agi | smol-developer     |
|--------------|----------|--------------------|----------|--------------------|
| Write File   | :x:      | :white_check_mark: | tbd      | :white_check_mark: |
| Read File    | :x:      | :x:                | tbd      | :x:                |
| Search File  | :x:      | :x:                | tbd      | :x:                |
Code
| Task                               | Auto-GPT | gpt-engineer       | mini-agi | …

Update Auto-GPT score

---

agbenchmark/conftest.py

Files in the workspace were being retained between test runs of the same module.
Change the workspace setup to run before each test
```shell
black .
isort .
mypy .
```

Clean up workspace between each test

---

.github/workflows/ci.yml
agbenchmark/utils.py

```shell
black .
isort .
mypy .
```

Fix cutoff errors

---

.github/workflows/ci.yml

```shell
black .
isort .
mypy .
```

Fix pipes issue

---

.github/workflows/ci.yml
.github/workflows/publish_package.yml
send_to_googledrive.py

- we need to cut releases of the benchmark
- the benchmark is pretty stable right now so let's do 10 runs and see which are the best agents !
```shell
black .
isort .
mypy .
```

Make spreadsheet dynamic

---

agbenchmark/conftest.py

Fixing dependencies issues with same_task false/true reports
```shell
isort .
mypy .
```

fix suite dependencies

---

.github/workflows/ci.yml

This PR fixes dynamic headers not working in CI. The issue stemmed from lockfile not being installed, and my testing environment not matching github actions. It is actually really annoying that Github doensnt open up their containers that they use. 😢
Here is the PR for the main script changes: https://github.com/Helicone/helicone/pull/645/files
You can now run dynamic headers for all tests using the following commands.
```bash
python3 -m pip install helicone
```
```python
from helicone.lock import HeliconeLockManager
HeliconeLockManager.write_custom_property("job_id", "1")
'''
Other Methods:
- write_custom_property(property_name: str, value: str) // Write a custom property
- remove_custom_property(property_name: str) // remove a custom property
- clear_all_properties() // clear all
''' …
```

added new script to fix dynamic headers

---

.flake8
.github/workflows/ci.yml
.gitmodules
agbenchmark/start_benchmark.py

Use beebot autopackai

---

.github/workflows/ci.yml

Benchmark all test

---

agbenchmark/reports/reports.py
agbenchmark/utils/challenge.py

Fix tests not being run

---

.gitmodules

Use Auto-GPT master

---

.github/workflows/ci.yml
send_to_googledrive.py

Currently, it's timeing out but doesn't send the results to google drive and doesn't commit so we loose the data
solution : put a timeout in the command itself
```shell
isort .
mypy .
```

Add timeout to agbenchmark

---

.github/workflows/ci.yml
agbenchmark/conftest.py

The previous PR added a timeout, but the reports couldn't finish, because pytest_sessionfinish wasn't hit.
```shell
isort .
mypy .
```

Add timeout that allows teardown

---

send_to_googledrive.py

Update autogpt back to where it was

---

pyproject.toml

Release 0.0.3

---

.github/workflows/publish_package.yml
agbenchmark/utils/dependencies/main.py
pyproject.toml

Release 0.0.4

---

agbenchmark/start_benchmark.py
poetry.lock
pyproject.toml

Remove baserun because api key issue

---

.gitignore
agbenchmark/conftest.py
agbenchmark/generate_test.py
agbenchmark/reports/reports.py
agbenchmark/start_benchmark.py
agbenchmark/utils/challenge.py
agbenchmark/utils/utils.py

agbenchmark start --mock --explore will only run challenges that are false in the challenges_already_beaten.json
I will document and add to the CI once we're certain this is good, I will also put challenges_already_beaten.json within the agent's folder
```shell
isort .
mypy .
```

Implement the 'explore' mode

---

.github/workflows/ci.yml
.gitmodules
agbenchmark/utils/dependencies/graphs.py
agbenchmark/utils/dependencies/main.py

- github.io is pretty useful to have versioned websites linked to each release => quick prototype.
- I need the next release of agbenchmark to release the skill tree, so we can get feedback from users.
```shell
isort .
mypy .
```

Sync skill tree to a versioned website

---

agbenchmark/generate_test.py
agbenchmark/utils/challenge.py

Add safety challenge

---

agbenchmark/utils/challenge.py

Fix linter
