Significant-Gravitas/Auto-GPT-Benchmarks

.github/workflows/smol-developer.yml, .gitmodules
- submodule
- benchmarks.py
- config.json
- regression_tests.json
=> Integrate smol developer with agbenchmark

README.md
Add readme to explain how to benchmark new agents
=> Explain how to benchmark new agents

agbenchmark/challenges/retrieval/r1/r1_test.py, agbenchmark/challenges/retrieval/r2/r2_test.py, agbenchmark/challenges/retrieval/r3/r3_test.py
```shell
black .
isort .
mypy .
```
=> Change test dependencies

.github/workflows/ci.yml, agbenchmark/start_benchmark.py
```shell
black .
isort .
mypy .
```
=> Rename '--reg' flag to '--maintain'

agbenchmark/challenges/memory/m2/artifacts/instructions_1.txt, agbenchmark/challenges/memory/m2/artifacts/instructions_2.txt, agbenchmark/challenges/memory/m2/artifacts/instructions_3.txt, agbenchmark/challenges/memory/m2/artifacts/instructions_4.txt, agbenchmark/challenges/memory/m2/artifacts/instructions_5.txt, agbenchmark/challenges/memory/m2/remember_multiple_ids_data.json, agbenchmark/challenges/memory/m2/remember_multiple_ids_test.py, agbenchmark/mocks/tests/basic_mocks.py, regression_tests.json
```shell
black .
isort .
mypy .
```
=> Add 'Remember multiple ids' memory challenge

agbenchmark/challenges/code/d2/artifacts_in/code.py, agbenchmark/challenges/code/d2/artifacts_in/test.py, agbenchmark/challenges/code/d2/artifacts_out/code.py, agbenchmark/challenges/code/d2/artifacts_out/test.py, agbenchmark/challenges/code/d2/d2_data.json, agbenchmark/challenges/code/d2/d2_test.py, agbenchmark/mocks/mock_manager.py, mypy.ini, regression_tests.json
```shell
black .
isort .
mypy .
```
=> Add "Debug code without guidance" challenge

agbenchmark/challenges/interface/search/artifacts_out/random_file.txt, agbenchmark/challenges/interface/search/data.json, agbenchmark/challenges/retrieval/r1/data.json, regression_tests.json
just cares about the ability to open the link. can the agent open the link?
search interface challenge
```shell
black .
isort .
mypy .
```
=> adding search interface challenge and cleaning repo

.github/workflows/ci.yml, agbenchmark/agent_interface.py, agbenchmark/challenges/test_all.py, poetry.lock, pyproject.toml
```shell
black .
isort .
mypy .
```
=> Fix tests ci

.github/workflows/ci.yml
```shell
black .
isort .
mypy .
```
=> All Agents log to helicone automatically

agbenchmark/agent_interface.py
```shell
black .
isort .
mypy .
```
=> Fix Auto-GPT looping forever

.github/workflows/ci.yml
```shell
black .
isort .
mypy .
```
=> Enable caching in Helicone

.github/workflows/ci.yml
```shell
black .
isort .
mypy .
```
=> Add custom properties to Helicone

.github/workflows/ci.yml
```shell
black .
isort .
mypy .
```
=> Update submodules and upload artifacts

README.md
Interface
| Task         | Results             |
|--------------|---------------------|
| Write File   | :white_check_mark:  |
| Read File    | :white_check_mark:  |
| Search File  | :x:                 |
Code
| Task                              | Results              |
|-----------------------------------|----------------------|
| Debug Simple Typo With Guidance   | :x:                  |
| Debug Simple Typo Without Guidance| :x:                  |
| Basic Code Generation             | :white_check_mark:   |
| Create Simple Web Server          | :x:                  |
Memory
| Task                                       | Results            |
|--------------------------------------------|--------------------|
| Basic Memory                               | :white_check_mark: |
| Remember …
=> Show Auto-GPT results

README.md
A repo built for the purpose of benchmarking the performance of agents far and wide, regardless of how they are set up and how they work
Radio chart for each agent coming soon !
:warning: These results are constantly evolving at the moment. We will publish an official benchmark result very soon.
Interface
| Task         | Results             |
|--------------|---------------------|
| Write File   | :white_check_mark:  |
| Read File    | :white_check_mark:  |
| Search File  | :x:                 |
Code
| Task                              | Results              |
|-----------------------------------|----------------------|
| Debug Simple Typo With Guidance   | :x:                  |
| Debug Simple Typo Without Guidance| :x:                  |
| Basic Code Generation             | …
=> Display smol-developer-results

README.md
A repo built for the purpose of benchmarking the performance of agents far and wide, regardless of how they are set up and how they work
Radio chart for each agent coming soon !
:warning: These results are constantly evolving at the moment. We will publish an official benchmark result very soon.
Interface
| Task         | Auto-GPT           | gpt-engineer       | mini-agi | smol-developer     |
|--------------|--------------------|--------------------|----------|--------------------|
| Write File   | :white_check_mark: | :white_check_mark: | tbd      | :white_check_mark: |
| Read File    | :white_check_mark: | :x:                | tbd      | :x:                |
| Search File  | :x:                | :x:                | tbd      | :x:                |
Code
| Task …
=> Display results per category

README.md
A repo built for the purpose of benchmarking the performance of agents far and wide, regardless of how they are set up and how they work
Radio chart for each agent coming soon !
:warning: These results are constantly evolving at the moment. We will publish an official benchmark result very soon.
Interface
| Task         | Auto-GPT           | gpt-engineer       | mini-agi | smol-developer     |
|--------------|--------------------|--------------------|----------|--------------------|
| Write File   | :x: | :white_check_mark: | tbd      | :white_check_mark: |
| Read File    | :x: | :x:                | tbd      | :x:                |
| Search File  | :x:                | :x:                | tbd      | :x:                |
Code
| Task                               | Auto-GPT           | …
=> Update auto gpt to current version of master

.github/workflows/ci.yml
```shell
black .
isort .
mypy .
```
=> Remove cache true on pr

.github/workflows/ci.yml, agbenchmark/utils.py
```shell
black .
isort .
mypy .
```
=> Allow change location of reports

.github/workflows/ci.yml
```shell
black .
isort .
mypy .
```
=> Update reports when pushing to master

.github/workflows/ci.yml, agbenchmark/utils.py
```shell
black .
isort .
mypy .
```
=> Use report location

.github/workflows/ci.yml, .gitignore, json_to_base_64.py, poetry.lock, pyproject.toml, send_to_googledrive.py
```shell
black .
isort .
mypy .
```
=> Push reports to google drive

.github/workflows/ci.yml, .gitmodules
- integrate beebot
- remove timeout because beebot is OP and solves too many challenges.
```shell
black .
isort .
mypy .
```
=> Integrate Beebot

.github/workflows/ci.yml
Because it makes the challenges non flaky. Cache is nice when you want to run a ton of tests on every Pull requests, in order to reduce costs. Currently we benchmark on push to master.
```shell
black .
isort .
mypy .
```
=> Disable cache

.github/workflows/publish_package.yml
```shell
black .
isort .
mypy .
```
=> Publish pypi package

pyproject.toml
```shell
black .
isort .
mypy .
```
=> Release 0.0.2

.gitmodules
=> Beat more challenges in Auto-GPT

.github/workflows/ci.yml, .gitmodules
- [C] I have run the following commands against my code to ensure it passes our linters:
```shell
isort .
mypy .
```
=> Uninstall agbenchmark then reinstall

.github/workflows/ci.yml
=> Fix helicone MITM

.github/workflows/ci.yml
=> Add api keys

agbenchmark/challenges/test_all.py, agbenchmark/conftest.py, agbenchmark/reports/utils.py, agbenchmark/utils.py
Just fixes with reports not being generated correctly
```shell
isort .
mypy .
```
=> hotfix reports

README.md
=> Update Scores Benchmark

.env.example, .gitmodules, agbenchmark/utils/challenge.py
=> Add llm eval

agbenchmark/conftest.py, agbenchmark/reports/ReportManager.py, agbenchmark/start_benchmark.py, poetry.lock, pyproject.toml, send_to_googledrive.py
=> Add helicone dynamic headers

.github/workflows/ci.yml, agbenchmark/config.json, agbenchmark/conftest.py, agbenchmark/reports/internal_info.json, get_data_from_helicone.py, poetry.lock, reports/Auto-GPT/file44_07-26-20-34.json, reports/Auto-GPT/file45_07-26-20-34.json, reports/Auto-GPT/file46_07-26-21-09.json
=> Add dynamic headers using environment variables

.github/workflows/ci.yml
=> Retry push until successful

send_to_googledrive.py
=> Fix export to gdrive

agbenchmark/agent_interface.py
=> Fix timeout not working

agbenchmark/utils/get_data_from_helicone.py
fixes string for Helicone API Key
=> Fix f-string get_data_from_helicone.py

README.md
I saw the link was wrong.
I fixed the link.
```shell
isort .
mypy .
```
=> Fix BeeBot link

agbenchmark/utils/get_data_from_helicone.py
```shell
isort .
mypy .
autoflake --remove-all-unused-imports --recursive --ignore-init-module-imports --ignore-pass-after-docstring agbenchmark"
agbenchmark/start_benchmark.py
```
=> Fix costs helicone

agbenchmark/utils/utils.py
```shell
isort .
mypy .
autoflake --remove-all-unused-imports --recursive --ignore-init-module-imports --ignore-pass-after-docstring agbenchmark"
agbenchmark/start_benchmark.py
```
=> Fix reports

.github/workflows/ci.yml
=> Reverse skip based on agent

reports/Auto-GPT/folder10_08-01-02-43/report.json, reports/Auto-GPT/folder11_08-01-03-21/report.json, reports/BabyAGI/folder11_08-01-02-46/report.json, reports/BabyAGI/folder12_08-01-03-23/report.json, reports/BabyAGI/folder16_08-01-19-54/report.json, reports/beebot/folder12_08-01-03-21/report.json, reports/beebot/folder3_07-31-03-06/folder11_08-01-02-42/report.json, reports/gpt-engineer/folder10_08-01-02-42/report.json, reports/gpt-engineer/folder11_08-01-03-20/report.json, reports/mini-agi/folder12_08-01-02-43/report.json, reports/mini-agi/folder13_08-01-03-21/report.json, reports/smol-developer/folder12_08-01-03-21/report.json
=> Remove high costs

.github/workflows/ci.yml
=> Update Auto-GPT and allow 1 specific agent to be run

agbenchmark/reports/ReportManager.py, agbenchmark/start_benchmark.py, agbenchmark/utils/utils.py, send_to_googledrive.py
=> Correct agent and benchmark commit sha

agbenchmark/utils/utils.py
=> fix-linter

send_to_googledrive.py
=> Add Test Suite to gdrive

agbenchmark/reports/reports.py
=> Fix "attempted" metric being incorrect

agbenchmark/reports/reports.py
=> Fix more attempted metrics not working

.github/workflows/ci.yml, agbenchmark/agent_interface.py, agbenchmark/utils/challenge.py
=> Add agent protocol interface test

mypy.ini
=> Add all agent protocol tests

agbenchmark/generate_test.py, agbenchmark/start_benchmark.py, agbenchmark/utils/challenge.py, agbenchmark/utils/utils.py
=> Add product advisor tests

agbenchmark/start_benchmark.py, poetry.lock, pyproject.toml
=> Integrate with baserun

agbenchmark/utils/dependencies/graphs.py, agbenchmark/utils/dependencies/main.py
=> See the task when clicking in the skill tree

.flake8, pyproject.toml
- cleanup skill tree
- remove isort and iflake on challenges
```shell
isort .
mypy .
```
=> Cleanup skill tree

.github/workflows/ci.yml
=> If regression tests empty continue

.github/workflows/ci.yml
=> Remember goal loss

agbenchmark/utils/dependencies/graphs.py
=> Use index.html instead of dependencies.html

pyproject.toml
=> Release 0.0.7

agbenchmark/generate_test.py, agbenchmark/utils/challenge.py
=> Fix agent protocol test

.github/workflows/ci.yml, .gitmodules, agbenchmark/utils/dependencies/graphs.py, backend/main.py, backend/requirements.txt, run.sh
FastApi backend, switching frontend to root
```shell
isort .
mypy .
```
=> init backend, fix frontend module

.github/workflows/ci.yml
=> Remove skill tree sync

.github/workflows/ci.yml
=> Fix linters and chrome selenium integration

.github/workflows/ci.yml, agbenchmark/utils/utils.py
=> Remove colons in timestamp

agbenchmark/challenges/memory/m1_id/data.json
=> Updatee cutoff for SuperAGI

agbenchmark/start_benchmark.py
It doesn't fix the problem but whatever
```shell
isort .
mypy .
```
=> remove warning

.github/workflows/ci.yml
=> Fix CI back

agbenchmark/challenges/verticals/code/3_url_shortener/artifacts_out/test.py, agbenchmark/challenges/verticals/code/3_url_shortener/artifacts_out/url_shortener.py, agbenchmark/challenges/verticals/code/3_url_shortener/data.json
=> Url shortener challenge
